# spring params
spring:
  application:
    name: dispatcher
  cloud:
    zookeeper:
      connect-string: 10.185.22.17:2181
#      dependencies:
#          agent:
#              path: /agent
#              loadBalancerType: ROUND_ROBIN
#              contentTypeTemplate: application/json
#              version: v1
#              required: false

# embedded server params
server:
  port: ${port}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

# logging params
logging:
  file: application.log
  level:
    org.apache.zookeeper.ClientCnxn: WARN

# auth params
auth:
  server:
    token_url: http://localhost:8088/oauth/token